### ISSUE TITLE
How to generate the item "Forward Segmentation" in the json file?

### ISSUE THREAD

**Issue by vangoghcat** [idilesenzulfikar/UNOVOST#2]
Thanks for your great work!
Now I see there is an item called "Forward Segmentation" in the json file, which seems to be generated from Optical Flow. But I dont find any code for generating it in the repository. Would you like to provide the relevant code?

**Comment by idilesenzulfikar** [comment]
You are right about generating forward segmentations. In order to extract optical flow vectors, we used optical-flow network in PremVOS.

**Comment by Meryl-Fang** [comment]
@fox16789  @idilesenzulfikar  Have you managed to use the code in PremVOS? I have tried really hard to generate ReID with little success (as for optical flow, I decided to use pytorch-pwc). Would really appreciate some pointers!

**Comment by idilesenzulfikar** [comment]
Can you please elaborate on the issue a little bit? If you have problems with PReMVOS, maybe @JonathonLuiten could be more helpful?

**Comment by JonathonLuiten** [comment]
The code in PReMVOS works out of the box for me. If you can't get it running for any reason, maybe open an issue with your problems on the PReMVOS repo?
