### ISSUE TITLE
training code?

### ISSUE THREAD

**Issue by noahcao** [idilesenzulfikar/UNOVOST#3]
Thanks for presenting so cool work!

I wonder if you could provide the code you used for training on davis and the guidelines about parameter settings / data organizations?

**Comment by idilesenzulfikar** [comment]
Hi Jinkun, 

The code in my GitHub repository is the one we used for the DAVIS Challenge. For the parameter settings, you can check our published paper. I am leaving the link of the paper in the below:

https://arxiv.org/abs/2001.05425

Best, 
Idil
