### ISSUE TITLE
Requirements and Other data

### ISSUE THREAD

**Issue by yahoo0742** [idilesenzulfikar/UNOVOST#5]
Thank you for your work. Can you please upload the versions of those libraries required, and the JSON files which are for DAVIS 2017 I reckon including masks, optical flow please? Thanks again!

**Comment by idilesenzulfikar** [comment]
Hi yahoo0742, 

First of all, sorry for the late reply.

You can find the versions of the libraries below: 
- cv2 		        3.4.2 
- PIL		        6.1.0 
- pycocotools 	2.0.2
- scipy 	        1.2.1
- pyyaml 	        5.1 
- pytorch	        1.4.0

I do not have enough space for uploading the JSON files for DAVIS 2017, sorry but I cannot help with that.

**Comment by yahoo0742** [comment]
Thank you for your answer. Are you able to upload a script of generating the masks and optical flow? Without an instruction, it's hard for people to generate data required for training. Thank you.

**Comment by idilesenzulfikar** [comment]
Hi,

You can find the instructions for generating the masks and optical flow vectors in README under Usage. 

Best,
Idil
