### ISSUE TITLE
Some question about data format in json file

### ISSUE THREAD

**Issue by DUT-CSJ** [idilesenzulfikar/UNOVOST#6]
Hi, @idilesenzulfikar 
Thanks for sharing your great work!
As a newcomer in computer vision community, I have some question about data format in json file.
The json file has some dict in it, each dict has some indexs such as 'bbox', 'score', 'segmentation'. The 'segmentation' has two elements: 'size' and 'counts', the 'counts' is str.
I don't know how to convert ndarray generated by mask RCNN to str.
So I wanna know what rule did you use to do this.
Looking forward to your reply.
Thanks.

**Comment by Davidyao99** [comment]
Hi, I was wondering if you manage to understand how the ndarray is converted to str? Thanks ;))
